name: PugFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0
description: Plugin for the Pug Freedom server. Contribute at github.com/rovertdude/PugFreedomMod
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, rovertdude, Duckeroo]

# plugin.yml is no longer used to define commands.
